name: codex-pr-sentinel

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  sentinel:
    if: github.event_name != 'issue_comment' || contains(github.event.comment.body, '@codex')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
        continue-on-error: false

      - name: Run Codex PR Sentinel
        run: |
          python tools/codex_pr_sentinel.py --event "${{ github.event_name }}" --payload '${{ toJson(github.event) }}'

      - name: Upload sentinel artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codex-pr-sentinel-report
          path: .codex/pr_sentinel_report.txt
          if-no-files-found: warn
